name: HatBlock
version: '1.0.0'
main: love.chihuyu.HatBlock
authors: [ Hirosuke ]
commands:
  hat:
    permission: hatblock.cmd.hat
    aliases:
      - hatblock
permissions:
  hatblock.cmd.*:
    default: op
    children:
      hatblock.cmd.hat: true
  hatblock.cmd.hat:
    default: true